# Generated by Django 3.2.8 on 2021-12-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contents',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.CharField(default='defalt', max_length=500),
            preserve_default=False,
        ),
    ]
